[new][bash] powerful bashrc framework

diff --git a/stow/bash/dot-bashrc b/stow/bash/dot-bashrc
--- a/stow/bash/dot-bashrc
+++ b/stow/bash/dot-bashrc
@@ -9,32 +9,51 @@ alias ls='ls --color=auto'
 alias grep='grep --color=auto'
 PS1='[\u@\h \W]\$ '
 
-# start::completion
-if [[ -d "${XDG_CONFIG_HOME:-${HOME}/.config}/bash_completion.d/" ]]; then
-  for bash_completion in "${XDG_CONFIG_HOME:-${HOME}/.config}/bash_completion.d/*"; do
-    [[ -r "${bash_completion}" ]] && . "${bash_completion}"
-  done
+# start::includes
+
+# It is recommended to prefix all filenames in those subdirectories with
+# a two-digit number and a dash, to simplify the ordering.
+
+CONFIG_D="${XDG_CONFIG_HOME:-${HOME}/.config}"
+ENVIRONMENT_D="${CONFIG_D}/bash_environment.d"
+COMPLETION_D="${CONFIG_D}/bash_completion.d"
+
+function source_unit() {
+  local unit_path=$1
+  local unit_file=$(basename ${unit_path})
+
+  if [[ ! -r "${unit_path}" ]]; then
+    echo "Error: fail to read ${unit_path}"
+    return
+  fi
+
+  local -i unit_no=${unit_file%%-*}
+  local unit_cmd=${unit_file#*-}
+
+  if [[ "${unit_file}" == "${unit_cmd}" ]]; then
+    echo "Warning: maybe 99-${unit_file} be nice"
+  elif (( unit_no >= 30 )); then
+    unit_cmd=${unit_cmd%.sh}
+    if ! command -v ${unit_cmd} &> /dev/null; then
+      echo "Error: command ${unit_cmd} not found, ignore ${unit_path}"
+      return
+    fi
+  fi
+
+  . "${unit_path}"
+}
+
+if [[ -d ${ENVIRONMENT_D} ]]; then
+  for unit in ${ENVIRONMENT_D}/*; do
+    source_unit "${unit}"
+  done; unset unit
 fi
-# end::completion
 
-# start::fzf
-if command -v fzf &> /dev/null; then
-  eval "$(fzf --bash)"
+if [[ -d ${COMPLETION_D} ]]; then
+  for unit in ${COMPLETION_D}/*; do
+    source_unit "${unit}"
+  done; unset unit
 fi
-[[ -r "${HOME}/.fzfrc" ]] && export FZF_DEFAULT_OPTS_FILE="${HOME}/.fzfrc"
-# end::fzf
 
-# start::proxy
-# go, dont use `go env -w`, some issue would be occur
-export GO111MODULE=on
-export GOPROXY=https://goproxy.io,direct
-# rustup
-export RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static
-# npm
-export NPM_CONFIG_REGISTRY=https://registry.npmmirror.com
-# end::proxy
-
-# start::deno
-[[ -r "${HOME}/.deno/env" ]] && . "${HOME}/.deno/env"
-# end::deno
+unset source_unit
 
